### ISSUE TITLE
Email refactor

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SRAM-deploy#270]
De nieuwe surfmailfilter heeft makkelijker/betere configuratiemogelijkheden voor het verzenden van mail.  Specifiek is er de mogelijkheid voor username/password authenticatie voor de mail.  

Dat moeten we in onze mailconfig implementeren.  @quartje kan de setup aan de kant van mailfilter doen en credentials geven.  Aan onze kant moeten we even nadenken of we de huidige situatie willen houden waar iedere host zelf mail stuurt, of dat we terug willen naar 1 smarthost (of 1 smarthost per omgeving).

Daarnaast kunnen we dan wellicht meteen DKIM/DMARC goed regelen.

**Comment by baszoetekouw** [comment]
Ik heb inmiddels instructies van Bart gekregen, dei stuur ik naar je door per mail.

**Comment by FlorisFokkinga** [comment]
@baszoetekouw , wat valt er hier te testen? Het verzenden van e-mails door SBS?

**Comment by baszoetekouw** [comment]
Ja, en dat heb ik al gedaan,  Ik zet hem door naar deploy.
