### ISSUE TITLE
As support, I want an email to be sent to eduTEAMS support automatically when a user account is deleted from SBS

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SRAM-deploy#272]
The email should contain the user's attributes and a request to delete the user from Perun.

Kunnen er meerdere addressen (of ccs) in de SBS mailconfig?

**Comment by oharsta** [comment]
Configure the following email for sending the deleted-user email.

**Comment by FlorisFokkinga** [comment]
I've deleted a user from TEST, using impersonation. I've asked eduTEAMS if they have received the email asking them to delete this user from Perun.

**Comment by baszoetekouw** [comment]
Nee, dit zou moeten werken.  IK heb  zojuist gechecked dat er alleen een mail naar sram-beheer wordt gestuurd.
De var `mail.eduteams_email` staat correct ingesteld op test.

**Comment by oharsta** [comment]
Fixed in https://github.com/SURFscz/SBS/commit/6d9ec6a8ecc43092be48db3e8ca3bb96426776e3

**Comment by baszoetekouw** [comment]
confirmed

**Comment by baszoetekouw** [comment]
confirmed
