### ISSUE TITLE
system integrity tools bekijken

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SRAM-deploy#282]
Check dat systeem in vertrouwde staat is, en wijzigingen opmerken.   ZIjn vast standaard tools voor.

**Comment by mrvanes** [comment]
https://github.com/Tripwire/tripwire-open-source

**Comment by baszoetekouw** [comment]
Ik was ook nog deze tegengekomen: https://www.la-samhna.de/samhain/s_documentation.html

@mrvanes zou jij deze twee eens kunnen uitproberen en je bevindingen (kort) kunnen opschrijven?  Ik ben vooral benieuwd wat voor security het toevoegt, en hoe het is beschermd tegen een aanvaller die de binary of databse van de tool zelf aanpast.

**Comment by baszoetekouw** [comment]
IA/IS doet er ook iets mee: https://confluence.ia.surf.nl/pages/viewpage.action?pageId=16924747
Specifiek gebruiken ze Suricata https://suricata.io/

**Comment by mrvanes** [comment]
https://github.com/aide/aide

**Comment by mrvanes** [comment]
Inzicht na discussie met Pieter: eigenlijk zou je OS integrity moeten testen op je virtualisatie platform, buiten je OS om en daarboven op de deploy specifieke files checken.

Een andere oplossing is eventueel met het package management tool de integriteit van alle OS packages checken:
https://manpages.org/debsums

**Comment by baszoetekouw** [comment]
Conclusie voor nu: weinig winst te behalen tenzij we iets in het VM-platform kunnen doen. Misschien later naar kijken als de SVP/CMP migratie dingus is afgerond.
