### ISSUE TITLE
Meer testusers voor VM

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SRAM-deploy#284]
Om de MFA flows in de VM goed te kunnen testen hebben we meer gebruikers nodig in de oidc-op:
 - user zonder acr met voPEI `<foo>@ssid.example.edu` en voEA `member@ssid.example.edu`
 - user zonder acr met voPEI `<foo>@mfa.example.edu` en voEA `member@mfa.example.edu`
 - user zonder acr met voPEI `<foo>@idp.example.edu` en voEA `member@idp.example.edu`

**Comment by mrvanes** [comment]
Fixed by https://github.com/SURFscz/SRAM-deploy/pull/285

**Comment by baszoetekouw** [comment]
Hoe zorg je daar dan dat die nieuwe users geen ACR-waarde krijgen?  Het lijkt (als ik de config goed begrijp) dat alle gebruikers automatisch in het authentication->mfa "profile" zitten (https://github.com/SURFscz/SRAM-deploy/blob/main/roles/oidc-op/templates/config_op.yaml.j2#L221).
Om MFA te kunnen testen heb ik juist gebruikers MET acr (de huidige admin voldoet daarvoor) en zonder acr nodig.

**Comment by mrvanes** [comment]
acr: urn:oasis:names:tc:SAML:2.0:ac:classes:InternetProtocolPassword (default als geen ACR gevraagd wordt) is ook goed genoeg.
Implementatie met keuze (radio) button in de login template van flask_example OP.
