### ISSUE TITLE
Nut/noodzaak van status.io bekijken voor SRAM (ism EduTEAMS)

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SRAM-deploy#287]
Naar aanleiding van Perun-disruptie van 22 mei 2022, zie https://wiki.surfnet.nl/pages/viewpage.action?pageId=66816894

**Comment by FlorisFokkinga** [comment]
Very simple existing SURF service status board: https://servicedesk.surf.nl/wiki/display/WIKI/Service+status
