### ISSUE TITLE
RStudio op SRAM (via reverse proxy oplossing)

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SRAM-deploy#288]
Nav verzoek Ivar: kijk of we RStudio ook kunnen ontslutien zoals we nu met etherpad en jupyter doen (achter proxy)

**Comment by mrvanes** [comment]
https://docs.rstudio.com/ide/server-pro/authenticating_users/proxied_authentication.html
https://docs.rstudio.com/ide/server-pro/r_sessions/pam_sessions.html

**Comment by baszoetekouw** [comment]
@mrvanes heb jij de pam-route nog uitgeprobeerd?

**Comment by baszoetekouw** [comment]
Gaat niet lukken denken we.  Even terugkoppelen naar Ivar.
