### ISSUE TITLE
Onderhoudsschermen

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SRAM-deploy#292]
De loadbalancer kan een custom scherm laten zien als er backends in onderhoud zijn (of anderszins kapot zijn).  Momenteel ziet dat er zo uit:

![Image](https://user-images.githubusercontent.com/1461740/175547217-7f113741-f573-4195-b256-dac3119d1471.png)

Ik zou hier graag een wat vriendelijkere melding/scherm/plaatje laten zien.  Kunnen jullie iets ontwerpen?

**Comment by baszoetekouw** [comment]
Een platte htmlpagina idd.  Plaatjes ed kunnen ook, maar die moeten waarschijnlijk worden geembed (maar dat kunnen we altijd achteraf nog in elkaar knutselen).

**Comment by FlorisFokkinga** [comment]
![undraw_server_down_s-4-lk](https://user-images.githubusercontent.com/80269262/176911474-006b4d02-cb40-4377-90e4-535aa449590a.svg)

## Oops, SURF Research Access Management is not available at the moment. Hopefully this is planned. We'll be back soon! ##

**Comment by FlorisFokkinga** [comment]
[SRAM_down.html.txt](https://github.com/SURFscz/SRAM-deploy/files/9354592/SRAM_down.html.txt)

**Comment by arnoutt** [comment]
Ziet er goed uit! Ik denk alleen dat het plaatje net iets te groot is, kan die nog wat kleiner?

**Comment by mrvanes** [comment]
Het lijkt er op dat de file te groot is ofzo, maar ik vind geen Google referentie
`haproxy[2293]: [ALERT] 331/082959 (2293) : parsing [/etc/haproxy/haproxy.cfg:36] : errorfile : '/etc/haproxy/errors/503.http': unable to add payload into the HTX message`

Wel de regel die verantwoordelijk is voor de error:
https://fossies.org/linux/haproxy/src/http_htx.c (regel 991)

**Comment by baszoetekouw** [comment]
Indeed, the docs mention this:

> The files are parsed when HAProxy starts and must be valid according to the
HTTP specification. They should not exceed the configured buffer size
(BUFSIZE), which generally is 16 kB, otherwise an internal error will be
returned.

http://cbonte.github.io/haproxy-dconv/2.2/configuration.html#errorfile%20%28Alphabetically%20sorted%20keywords%20reference%29

I'll try to reduce the size of the page.
