### ISSUE TITLE
make sure rejected ldap connection attempts are logged

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SRAM-deploy#293]

**Comment by mrvanes** [comment]
specifiek wil ik en log regeltje als deze acl faalt:
https://github.com/SURFscz/SRAM-deploy/blob/main/roles/lb_haproxy/templates/haproxy.cfg.j2#L156
[haproxy.cfg.j2](https://github.com/SURFscz/SRAM-deploy/blob/main/roles/lb_haproxy/templates/haproxy.cfg.j2)

`tcp-request connection reject unless ldap_sbs_allow or ldap_local_allow or ldap_vpn_allow`

**Comment by baszoetekouw** [comment]
zojuist gezien op vm
