### ISSUE TITLE
ldap fence script fixen

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SRAM-deploy#294]
verwijst nu nog hard naar vm bv

**Comment by mrvanes** [comment]
https://github.com/SURFscz/SRAM-deploy/blob/main/roles/lb_haproxy/templates/fence.sh.j2

**Comment by baszoetekouw** [comment]
Ik snap nog steeds niet helemaal wat er gebeurt.  Als ik nu 1 ldap machine reboot (bv) en de ping timet out, dan wordt de hele ldap frontend gedisabled.  Dat lijkt me niet de bedoeling?

**Comment by baszoetekouw** [comment]
Ik heb voor v15 de fencing even gedisabled.

**Comment by baszoetekouw** [comment]
Obsolete door #350 
In dat geval kunnen we de fence scripts gewoon verwijderen.

**Comment by baszoetekouw** [comment]
confirmed.
