### ISSUE TITLE
SBS debug logging terughalen

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SRAM-deploy#314]
Het zou handig zijn als sbs direct naar de systemd journal zou kunnen loggen.  Het package `python-systemd` heeft een journal handler class voor het standaard python loggin framework dat hiervoor te gebruiken zou moeten zijn: https://github.com/systemd/python-systemd

Het is denk ik wel handig om in de config file te kunnen switchen tussen loggen naar file en naar de journal (of wellicht beide).

python-systemd does not run on mac.

**Comment by baszoetekouw** [comment]
Werkt nu al na https://github.com/SURFscz/SRAM-deploy/issues/313

**Comment by mrvanes** [comment]
Deels opgelost?
journalctl -u sram-sbs bevat nu wel SBS logs, en deze DEBUG regel verschijnt er wel:
```DEBUG [apscheduler.scheduler] Next wakeup is due at 2022-12-13 04:00:00+00:00 (in 60450.598118 seconds)```

maar deze test (in __main__.py) dan weer niet, maar wel in log/sbs_debug.log
```logger.debug("Debug logging test")```

**Comment by baszoetekouw** [comment]
Ja, er gaat nog iets niet helemaal goed; die python logger meuk is ene beetje Black Magick, dus misschien moeten we daar nog even goed naar kijken.

**Comment by baszoetekouw** [comment]
dit lijkt nu op prod "gewoon" te werken.  Ik sluit dit ticket dus maar.
