### ISSUE TITLE
Adapt Mock-OP so it understands acr_values and can perform SFO-requests to SBS

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SRAM-deploy#315]
Het zou handig zijn als we deze hele flow, dus:

    SBS zet acr_values in authn request
    OP doet SFO-request
    OP stuurt acr terug naar RP
    ook kunnen testen met de test-op.

Is dat haalbaar?

@mrvanes:
oidc-op is aangepast door Roland en in local test werkt het, het wachten is nu op het accepteren van de PR's en een nieuwe oidc-op pip versie.

**Comment by mrvanes** [comment]
Ik snap niet goed wat het verschil is met deze functionaliteit?
https://github.com/SURFscz/SRAM-deploy/pull/285

**Comment by baszoetekouw** [comment]
#285 gaat over standaard gebruikers die altijd een bepaalde 2FA-methode moeten gebruiken; deze story gaat over het dynamisch kunnen aanvragen van een ACR-waarde.  Dus als SBS in de `authn_request` de `acr_values` zet, moet de mock-idp daar adequaat op reageren.

We willen straks dat SBS hard een lijstje van ACRs gaat vragen aan alle IdPs;  deze functionaliteit is dan nodig om dat te kunnen testen.

**Comment by mrvanes** [comment]
Ik denk dat er een misverstand is over hoe #285 geimplementeerd is, die doet precies wat je vraagt, namelijk adequaat reageren op een URL met urn:oasis:names:tc:SAML:2.0:ac:classes:InternetProtocolPassword of https://refeds.org/profile/mfa onafhankelijk van de gebruiker die authenticeert.

**Comment by baszoetekouw** [comment]
f2f overlegd: @mrvanes heeft gelijk, dit is al geimplementeerd.
