### ISSUE TITLE
As a CO admin I want to be warned if an email invite cannot be sent

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SRAM-deploy#316]
Als de e-mail naar een gebruiker niet kan worden afgeleverd, zou dat moeten worden teruggemeld aan de uitnodiger/admin. Lijkt me een nuttige usecase, maar tegelijk is dit behoorlijk complex, en ik weet zo even niet hoe we dit technisch zouden moeten regelen.

**Comment by baszoetekouw** [comment]
@quartje Kunnen nwe op de een of andere manier feedback krijgen van Mailfilter als een mail niet kan worden afgeleverd?

**Comment by quartje** [comment]
Als een bericht niet kan worden afgeleverd sturen we een bounce naar de envelope sender. Verder kan ik niet zoveel voor je betekenen

**Comment by baszoetekouw** [comment]
technisch lastig zonder hele duidelijk meerwaarde.  Nu niet.
