### ISSUE TITLE
UI-love voor demo-sp.sram.surf.nl

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SRAM-deploy#320]
- [x] Zowel de landingpagina, de SAML-SP en de OIDC-RP zijn nu tamelijk kaal; dat mag wel iest fancier, zie bv https://demosp.surfconext.nl/ ter inspiratie

- [x] Ook moeten de OIDC-RPs nog op de landingspagian worden vermeld.

- [ ] Verder zou het handig zijn als we een directe link (iets als `https://demo-sp/logjn-saml-acc`) zouden hebben om in te loggen (en die dan redifect naar de goede SSP-link) waar je makkelijker naar kan linken dan naar de directe SSP-loginlink.

**Comment by mrvanes** [comment]
Links zijn eigenljk al behoorlijk fancy:
Voor SAML: https://demo-sp.sram.surf.nl/auth/[test|acc|prd]
Voor OIDC: https://demo-sp.sram.surf.nl/rp/[test|acc|prd]

**Comment by baszoetekouw** [comment]
perfect!
