### ISSUE TITLE
OIDC-op draait in debug mode

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SRAM-deploy#322]
OIDC-op draait in debug mode.  Dat is niet de bedoeling, want dat geeft security gedoe (ook al gebruiken we dit niet in productie).

de debug vlag in `oidc-op/example/flask_op/config_op.json` moet op `False`.

**Comment by mrvanes** [comment]
https://github.com/SURFscz/SRAM-deploy/pull/333
