### ISSUE TITLE
OIDC-op niet als root draaien

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SRAM-deploy#323]
De systemd service van oidc-op draait nu als root.  (zie https://github.com/SURFscz/SRAM-deploy/blob/main/roles/oidc-op/templates/oidc-op.service.j2#L5)

Dat is nergens voor nodig;  graag aanpassen zodat hij als een DynamicUser draait (naast non-privileged is die ook nog verder afgesloten van het filesystem).  Zie https://github.com/SURFscz/SRAM-deploy/blob/main/roles/aclsync/templates/sram_aclsync.service.j2 voor een voorbeeld.

**Comment by mrvanes** [comment]
https://github.com/SURFscz/SRAM-deploy/pull/333
