### ISSUE TITLE
SBS database user heeft minder permissies nodig

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SRAM-deploy#326]
The sbs database user heeft minder permissies nodig.  INSERT, UPDATE, SELECT zou voldoende moeten zijn als SBS zelf geen databasemigraties hoeft te doen (zie #324).

**Comment by mrvanes** [comment]
First attempt https://github.com/SURFscz/SRAM-deploy/pull/343

**Comment by baszoetekouw** [comment]
Is idd gefixed met #343
