### ISSUE TITLE
Add password to redis

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SRAM-deploy#327]
Redis is currently running without authentication.  That's not really an issue, as the network is properly secures using security groups .  Nevertheless, it adds an extra layer of protection to add a password here.

Taken:

- [x] password op de redis in vm
- [x] password in SBS opvoeren
- [x] password zetten ip de AWS redis. Wellicht kan dat vanuit ansible, maar anders moet het met terraform.

**Comment by baszoetekouw** [comment]
See https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/auth.html

**Comment by baszoetekouw** [comment]
Voor de release moet dit worden gecombineerd met een terraform redis update.

**Comment by baszoetekouw** [comment]
Helaas, er gaat op test nog iets mis: bij het aanzetten van een auth-token zet AWS ook direct TLS aan, en dat snapt SBS nog niet.  @mrvanes heb jij tijd om dit te debuggen?  
De SBS config van redis staat hier: https://github.com/SURFscz/SBS/blob/main/server/db/redis.py

Vanaf app1-tf1 kan ik de redis bereiken met
```
redis-cli --tls -h master.sram-tst.ffqqpq.euc1.cache.amazonaws.com -a $PASSWD
```
Maar in SBS werkt het niet zomaar (zelf niet als ik ssl met de hand aanzet in de SBS code).  Vast iets met SSL certificaten.

**Comment by mrvanes** [comment]
Waarschijnlijk iets met eventlet, monkey_patching en SSL/sockets

**Comment by baszoetekouw** [comment]
@oharsta @mrvanes hebben we hier inmiddels een oplossing voor?  Of duidelijkheid wat het probleem is?

**Comment by mrvanes** [comment]
Ik niet iig, dus ik ben bang dat het kiezen wordt tussen FlaskIO/eventlet of een password op de redis DB?

**Comment by oharsta** [comment]
Nieuwe build loopt met daarin https://github.com/SURFscz/SBS/commit/71c33f4cad9eb130228345a7bcbf00c29b026411. Even afwachten

**Comment by oharsta** [comment]
Helaas. Dat lost het probleem niet op.

**Comment by baszoetekouw** [comment]
Achterliggende bug in eventlet is deze: https://github.com/eventlet/eventlet/issues/692

Heb daar hulp aangeboden om eventlet te fixen; @mrvanes werkt aan een tijdelijke fix voor SBS.
