### ISSUE TITLE
Zabbix role module naar upstream

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SRAM-deploy#358]
De zabbix_role module lijkt goed te werken.  Het lijkt me toch wel een goed idee om dit verder uit te boetseren tot een module die we naar upstream kunnen sturen.

Misschien eerst even informeren of ze open staan voor een PR voor zabbix rollen?

**Comment by mrvanes** [comment]
https://gitter.im/community-zabbix/community

**Comment by mrvanes** [comment]
https://github.com/ansible-collections/community.zabbix/pull/820
