### ISSUE TITLE
geen change status bij ldap-wijzigingen

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SRAM-deploy#360]
Probleem is dat deze task https://github.com/SURFscz/SRAM-deploy/blob/main/roles/ldap/tasks/main.yml#L112-L123 nooit changes aangeeft.  Als je bv het `ldap_loglevel` wijzigt, zou hij dat moeten laten zijn tijden de deploy.  Dat gebeurt nu niet.

Idealiter laat hij bij `ansible --diff` ook zijn _wat_ de wijziging is (maar ik weet niet of dat mogelijk is).

**Comment by mrvanes** [comment]
Laten we alsjeblieft voor eens en voor altijd onthouden dat dit niet gaat lukken tot dit issue opgelost is:
https://github.com/ansible-collections/community.general/issues/977

ldapmodify geeft altijd exitcode 0 als er geen error opgetreden is, zowel voor een modify die iets verandert als een waar niks gebeurt, omdat dat een valide uitkomst is (voor ldapmodify).

**Comment by baszoetekouw** [comment]
Ja, maar in dit geval gebruik je ldap_ttrs helemaal niet, maar je eigen ldap python script.  Daar kunnen we het prima goed doen volgens mij.

**Comment by baszoetekouw** [comment]
Dat is nog een beter idee idd

**Comment by mrvanes** [comment]
Een kijken hoe ver we komen
https://github.com/ansible-collections/community.general/pull/5385

**Comment by mrvanes** [comment]
https://github.com/SURFscz/SRAM-deploy/pull/363
