### ISSUE TITLE
Maak in mailtext duidelijk om welke omgeving het gaat

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SRAM-deploy#362]
Je kunt nu niet zien of "Collaboration suspended notification" of test, acc, of prod gaat,.

Bij test/acc iets toevoegen (in body en subject).  Prod zo laten als nu

**Comment by oharsta** [comment]
Fixed in https://github.com/SURFscz/SBS/commit/a531317ab7dd8b2729500c5d9f3200738602c09a

**Comment by baszoetekouw** [comment]
Dit is wel een beetje een nare oplossing, zo hard gekoppeld aa het domein "sram.surf.nl".
Kunnen we er niet een config optie `environment_disclamer` oid maken, die zowel in `disclaimer.css` terecht komt als in de mails?

**Comment by baszoetekouw** [comment]
Het werkt overigens wel goed :)

**Comment by oharsta** [comment]
https://github.com/SURFscz/SBS/commit/1566f92cb5feec18c055fe7ed4649932ad139b3e

**Comment by baszoetekouw** [comment]
ok
