### ISSUE TITLE
Deploy fails because of missing dependencies of new mysql driver

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SRAM-deploy#370]
See eg https://github.com/SURFscz/SRAM-deploy/actions/runs/3468509411/jobs/5794401176

**Comment by mrvanes** [comment]
Among others https://github.com/SURFscz/SRAM-deploy/commit/74e183cc8a80f407d6bda9bf9a8b6fc56cca973b

**Comment by baszoetekouw** [comment]
werkt.
