### ISSUE TITLE
Trap SRAM-deploy CO run af bij nieuwe SBS release

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SRAM-deploy#375]
We zien nu regelmatig dat een nieuwe SBS-release de SRAM-deploy CI kapot maakt (bv door aangepaste labels op buttons).  Daarom zou het handig zin om bij een nieuwe SBS-release (dus als deze actie wordt getirggerd: https://github.com/SURFscz/SBS/blob/main/.github/workflows/main.yml#L245) ook de SRAM-deploy CI's af te trappen

zie bv https://github.com/orgs/community/discussions/26323

**Comment by mrvanes** [comment]
Meest bruikbare voorbeeld obv actions/github-script@v6
https://github.com/orgs/community/discussions/26323#discussioncomment-3343871

**Comment by baszoetekouw** [comment]
Fixed in https://github.com/SURFscz/SBS/commit/11f6dfc8a776c202a7a6e1b1a014db44fd5ba09a and https://github.com/SURFscz/SBS/commit/85592896dffa7864995ba3665635bd793d4f9a44
