### ISSUE TITLE
Rewrite role client_base to use new simplesaml role

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SRAM-deploy#386]
Er is sinds kort een generieke Simplesaml rol, die je op deze manier kan aanroepen: https://github.com/SURFscz/SRAM-deploy/blob/main/roles/demo-sp/tasks/main.yml#L27-L34

Graag deze ook gebruiken voor de rollen `ci-test` en `client-base`, zodat we alle logica maar op 1 plek hebben en we makkelijk SSP kunnen upgraden.

**Comment by mrvanes** [comment]
En tegelijk migreren naar nginx ipv apache2 neem ik aan?
