### ISSUE TITLE
Etherpad demo opnemen in ansible 

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SRAM-deploy#390]
De etherpad demo die nu nog op https://demo.sram.surf.nl/ staat willen we verduurzamen.  Hij moet daarom in ansible worden opgenomen en netjes in de deploy mee.

Draait in een docker via https://github.com/SURFscz/demos/tree/WNASCdemoheksels/ReverseProxy

**Comment by mrvanes** [comment]
En op welke host/hoe gaan we die container(s) dan starten? Hoe wordt de dienst dan naar buiten exposed?

**Comment by baszoetekouw** [comment]
werkt

**Comment by baszoetekouw** [comment]
PR moet nog wel een beetje opgekuist

**Comment by baszoetekouw** [comment]
PR was al onderdeel van Wordpress demo merge.
