### ISSUE TITLE
Betere monitoring van echte SAML en OIDC logins

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SRAM-deploy#393]
Naar aanleiding van https://wiki.surfnet.nl/display/coininfra/2023-01-16+SRAM+storing+Entitlements

Bij deze storing leverde SBS wel de goede entitlements door in `proxy_authz`, maar filterde Satosa die weg.

We willen daarom actief monitoren dat de hele loginketen (SAML, OIDC, `proxy_authz`) correct functioneert.  Dat betekent dat we willen testen dat:
 - een OIDC login werkt en dat de gebruiker alle verwachte claims doorkrijgt
 - een SAML login werkt en dat de gebruiker alle verwachte attributen doorkrijgt
 - het `proxy_authz` endpoint de goede attributen uitlevert

Hopelijk kunnen we hiervoor voortbouwen op de CI/Behave tests die we al hebben.  Ik stel voor om een EduID-gebruiker (voor nu, wellicht kunnen we later een dedicated test-IdP gebruiken) in een aantal vaste COs te stoppen die alleen toegang hebben tot de Demo RP en Demo SP. We richten dan een proces in dat regelmatig (zeg, elk kwartier) een SAML en een OIDC login doet en dat rapporteert via Zabbix.

Dit zou kunnen draaien op de (nog steeds maar half ingerichte) bhr13.

**Comment by baszoetekouw** [comment]
@mrvanes ik denk dat we dit gewoon kunnen implementeren op bhr13.  Zou jij kunnen kijken of je iets in elkaar kunt knutselen (misschien eerst even op acc)?

**Comment by mrvanes** [comment]
https://github.com/SURFscz/monitoring/commit/b705e36a20202db2a791046589feafad07db070e

**Comment by baszoetekouw** [comment]
alleen nog wat config verplaatsen in de PR

**Comment by baszoetekouw** [comment]
lijkt te werken nu; valt af en toe nog wle om, dus moeten we even in de gaten houden
