### ISSUE TITLE
HAproxy doesn't detect that SBS is not running if the nginx stays up

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SRAM-deploy#415]
Haproxy currently checks the root on the SBS backend.  However, the root keep being available if SBS itself (wsgi) is down.  It should check `/health` instead.

It is probably easiest to also add `/health` on meta.sram.nl, rather than making the check endpoint configurable.

**Comment by mrvanes** [comment]
Ik ben uiteindelijk toch voor een config optie gegaan, ivm de andere http backends in VM die ook geen /health endpoint hebben.

**Comment by baszoetekouw** [comment]
getest op acc
