### ISSUE TITLE
Monitor quality of SRAM metadata in zabbix

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SRAM-deploy#416]
Aka: use https://github.com/SURFscz/mdparser/ to check if metadata keys are not about to expire.   Makes it also easy to add other tests in the future.

**Comment by mrvanes** [comment]
Zabbix heeft nu 2 nieuwe items op app1-tf1: "MDparser proxy_idp" en "MDparser proxy_sp".
De ouptut van MDparser is normaliter leeg, twee Triggers bytelength() zijn toegevoegd voor outputs anders dan leeg.

**Comment by baszoetekouw** [comment]
zie https://zabbix.sram.surf.nl/triggers.php?form=update&triggerid=25948&context=host en https://zabbix.sram.surf.nl/triggers.php?form=update&triggerid=25948&context=host
