### ISSUE TITLE
uitbreiding authorizaties ldap

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SRAM-deploy#421]
Vanaf relaese v20 hebben we lokale (readonly) ldap-gebruikers (zie https://github.com/SURFscz/SRAM-deploy/pull/356).  Hier wil ik graag nog twee extra features toevoegen:
  - alleen gebruikers in een specifieke groep (zoals gedefinieerd op https://gitlab.surf.nl/sram/sram-deploy-aws/-/blob/main/users.yml) krijgen een ldap-account
  - als een gebruiker uit die groep verdwijnt (of helemaal verdwijnt) moet de ldap-account ook worden verwijderd.

**Comment by mrvanes** [comment]
Moet nog een klap krijg over de definitieve voorwaarde voor inclusie (hardcoded groepnaam of ansible groep conf?)

**Comment by baszoetekouw** [comment]
getest en goed vars voor tst, acc, prd toegevoegd.  Werkt!
