### ISSUE TITLE
New demo-sp ssp config ignore voPerson attributes

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SRAM-deploy#422]
Probably the voPerson/oid/readablenames translation is not active anymore?

**Comment by mrvanes** [comment]
Extended voPerson oid2name attributemaps didn't make it into 1.19.7 and are only available in 2.0.0-RC3 atm.

**Comment by mrvanes** [comment]
voPerson attributes are now a part of oid2name attributemaps, but we need to decide about known attributes https://github.com/SURFscz/SRAM-deploy/blob/main/roles/demo-sp/files/auth.php#L16

**Comment by baszoetekouw** [comment]
works now.
