### ISSUE TITLE
Zabbix module migratie naar "httpapi"

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SRAM-deploy#428]
Zabbix modules geven gezeur zoals dit:
```
[WARNING]: Option "server_url" is deprecated with the move to httpapi
connection and will be removed in the next release
[WARNING]: Option "login_user" is deprecated with the move to httpapi
connection and will be removed in the next release
[WARNING]: Option "login_password" is deprecated with the move to httpapi
connection and will be removed in the next release
```

Die upgrade naar httpapi is echter niet triviaal.  Zie bv https://app.gitter.im/#/room/#community-zabbix_community:gitter.im

Het lijkt er dan op dat we de zabbix host in alle inventories moeten definieren met een `connection_type: "httpapi"`, en dam voor die host globaal de variabelen zetten zoals hierbovenaan de voorbeelden uitgelegd: https://docs.ansible.com/ansible/latest/collections/community/zabbix/zabbix_user_module.html#examples

Ik heb even snel een poging gewaagd, maar kreeg het niet aan de praat.  Poging staat  in feature/zabbix-httpapi branch. Als je daar in de inventory ook de zabbix host definieert, doet hij iets (maar nog steeds niet veel).

**Comment by mrvanes** [comment]
Onze VM's zitten nu op Deb11 en voor de zabbix-agent installeren we nu zabbix repo 5.4, maar de zabbix-server rol ondersteunt 5.4 niet meer op Deb11 (https://github.com/ansible-collections/community.zabbix/blob/main/docs/ZABBIX_SERVER_ROLE.md#zabbix-versions) waardoor ik hier lokaal geen test zabbix server op kan spinnen om het httpapi gebeuren te testen.
Ik begreep dat we binnenkort naar bookworm gaan en misschien is dat ook een mooi moment om zabbix dan naar 6.x te tillen en lokaal in de docker toch ook maar zabbix-server op bhr te installeren zodat we de zabbix provisioning lokaal een beetje kunnen testen?
Naar test of acc testen lukte destijds ook niet omdat er iets met secrets was waar ik niet bij mocht... Daar zou je ook naar kijken toen?
