### ISSUE TITLE
SCIM monitoring

### ISSUE THREAD

**Issue by FlorisFokkinga** [SURFscz/SRAM-deploy#430]
Suggestion: sync from SCIM PROD and cehck that result is as we expect

zie ook https://github.com/SURFscz/SRAM-deploy/issues/424

**Comment by mrvanes** [comment]
https://github.com/HarryKodden/scim

**Comment by mrvanes** [comment]
https://github.com/SURFscz/SCIM-server
https://github.com/SURFscz/SRAM-deploy/pull/458
