### ISSUE TITLE
X-content-type nosniff toevoegen

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SRAM-deploy#460]

**Comment by mrvanes** [comment]
CSP Policy in haproxy conf ofzo?

**Comment by baszoetekouw** [comment]
Zoals al besproken gaat het hier om de http redirects in nginx/apache

**Comment by mrvanes** [comment]
Al gefixt? https://github.com/SURFscz/SRAM-deploy/commit/670635981ea76c6a8c0cc25222f6b5b4109fcee1
En zo niet, noteer even het endpoint dan.
