### ISSUE TITLE
Logs moeten via syslog naar centrale logserver gestuurd worden

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SRAM-deploy#500]

**Comment by baszoetekouw** [comment]
in jira https://jira.ia.surf.nl/browse/SRAM-161

**Comment by mrvanes** [comment]
https://github.com/mrvanes/rsyslog/tree/main

**Comment by baszoetekouw** [comment]
@mrvanes can you move the repo to SURFscz?

**Comment by baszoetekouw** [comment]
On hold until we have a working upstream syslog server.

**Comment by mrvanes** [comment]
Added to gitlab.surf.nl sram-tools

**Comment by baszoetekouw** [comment]
Dit gaat vanzelf als we naar de SC infra migreren.
