### ISSUE TITLE
haproxy "sram is not available" uses wrong colout for orange bar

### ISSUE THREAD

**Issue by FlorisFokkinga** [SURFscz/SRAM-deploy#507]
It is based on the former style header and footer.

https://github.com/SURFscz/SRAM-deploy/blob/main/roles/lb_haproxy/templates/error_sram_down.html.j2

![Image](https://github.com/SURFscz/SRAM-deploy/assets/80269262/dc4074d1-799d-42ea-bb88-99c6f6666fda)

**Comment by mrvanes** [comment]
Where is the new style header and footer?

**Comment by FlorisFokkinga** [comment]
From the normal SBS UI.

**Comment by baszoetekouw** [comment]
![Image](https://github.com/SURFscz/SRAM-deploy/assets/1461740/dd00cc1e-4f60-48c6-bb23-52aa5e719b37)

**Comment by FlorisFokkinga** [comment]
Sorry, but that's not the standard footer. :)

This is, but hide the language chooser if it doesn't work.

![image](https://github.com/SURFscz/SRAM-deploy/assets/80269262/c6d0e60a-a4aa-4089-a662-23bc98fbe5dd)

**Comment by mrvanes** [comment]
https://github.com/SURFscz/SRAM-deploy/pull/512

**Comment by baszoetekouw** [comment]
![Screenshot 2024-05-02 at 18 18 02](https://github.com/SURFscz/SRAM-deploy/assets/1461740/0ff6de53-44c8-4a0e-9a9d-bc0e824dcb15)
 
@FlorisFokkinga
