### ISSUE TITLE
Working pam-demo for acc

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SRAM-deploy#525]

**Comment by mrvanes** [comment]
https://ssh-demo-acc.lab.surf.nl/ niet goed genoeg?

**Comment by logan-life** [comment]
Bas to review PR and merge.

**Comment by baszoetekouw** [comment]
waiting for SVP ACL change

**Comment by logan-life** [comment]
https://jira.ia.surf.nl/servicedesk/customer/portal/1/ISSD-28458

**Comment by logan-life** [comment]
ACL ticket marked as Done, should be ready for test

**Comment by baszoetekouw** [comment]
Works on acc now with service https://acc.sram.surf.nl/services/62
ssh://sram@demo-ssh.sram.

![Screenshot 2024-09-10 at 13 11 19](https://github.com/user-attachments/assets/b019359d-c618-4f08-9e3b-db70fc75e74e)
surf.nl:2022/
